-- 시퀀스 삭제
DROP SEQUENCE SEQ_USERS_NO;
DROP SEQUENCE SEQ_CUSTOMER_NO;
DROP SEQUENCE SEQ_ADMIN_ROLE_CODE;
DROP SEQUENCE SEQ_ADMIN_NO;
DROP SEQUENCE SEQ_BOARD_CATEGORY_NO;
DROP SEQUENCE SEQ_BOARD_NO;
DROP SEQUENCE SEQ_BOARD_REPLY_NO;
DROP SEQUENCE SEQ_PRODUCT_CATEGORY_NO;
DROP SEQUENCE SEQ_PRODUCT_NO;
DROP SEQUENCE SEQ_PRODUCT_IMAGE_NO;
DROP SEQUENCE SEQ_PRODUCT_REVIEW_NO;
DROP SEQUENCE SEQ_PRODUCT_REVIEW_REPLY_NO;
DROP SEQUENCE SEQ_CART_NO;
DROP SEQUENCE SEQ_CART_ITEM_NO;
DROP SEQUENCE SEQ_ORDERS_NO;
DROP SEQUENCE SEQ_ORDER_ITEM_NO;
DROP SEQUENCE SEQ_DELIVERY_NO;
DROP SEQUENCE SEQ_EVENT_NO;
DROP SEQUENCE SEQ_COUPON_NO;
DROP SEQUENCE SEQ_EMAIL_LOG_NO;
DROP SEQUENCE SEQ_USER_COUPON_NO;
DROP SEQUENCE SEQ_USER_LOG_NO;


-- 1. USERS 테이블의 USER_NO 시퀀스
CREATE SEQUENCE SEQ_USER_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 2. CUSTOMER 테이블의 USER_NO는 USERS 테이블의 USER_NO와 동일한 시퀀스를 사용합니다.

-- 3. ADMIN_ROLE 테이블에는 NUMBER 타입의 PRIMARY KEY가 없으므로 시퀀스 생성 불필요

-- 4. ADMIN 테이블의 USER_NO는 USERS 테이블의 USER_NO와 동일한 시퀀스를 사용합니다.

-- 5. BOARD_CATEGORY 테이블에는 NUMBER 타입의 PRIMARY KEY가 없으므로 시퀀스 생성 불필요

-- 6. BOARD 테이블의 BOARD_NO 시퀀스
CREATE SEQUENCE SEQ_BOARD_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 7. REPLY 테이블의 REPLY_NO 시퀀스
CREATE SEQUENCE SEQ_BOARD_REPLY_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 8. PRODUCT_CATEGORY 테이블에는 NUMBER 타입의 PRIMARY KEY가 없으므로 시퀀스 생성 불필요

-- 9. PRODUCT 테이블의 PRODUCT_NO 시퀀스
CREATE SEQUENCE SEQ_PRODUCT_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 10. PRODUCT_IMAGE 테이블의 IMAGE_NO 시퀀스
CREATE SEQUENCE SEQ_IMAGE_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 11. PRODUCT_REVIEW 테이블의 REVIEW_NO 시퀀스
CREATE SEQUENCE SEQ_REVIEW_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 12. PRODUCT_REVIEW_REPLY 테이블의 REPLY_NO 시퀀스
CREATE SEQUENCE SEQ_PRODUCT_REVIEW_REPLY_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 13. CART 테이블의 CART_NO 시퀀스
CREATE SEQUENCE SEQ_CART_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 14. CART_ITEM 테이블의 CART_ITEM_NO 시퀀스
CREATE SEQUENCE SEQ_CART_ITEM_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 15. ORDERS 테이블의 ORDER_NO 시퀀스
CREATE SEQUENCE SEQ_ORDER_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 16. ORDER_ITEM 테이블의 ORDER_ITEM_NO 시퀀스
CREATE SEQUENCE SEQ_ORDER_ITEM_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 17. DELIVERY 테이블의 DELIVERY_NO 시퀀스
CREATE SEQUENCE SEQ_DELIVERY_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 18. EVENT 테이블의 EVENT_NO 시퀀스
CREATE SEQUENCE SEQ_EVENT_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 19. COUPON 테이블의 COUPON_NO 시퀀스
CREATE SEQUENCE SEQ_COUPON_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 20. EMAIL_LOG 테이블의 EMAIL_LOG_NO 시퀀스
CREATE SEQUENCE SEQ_EMAIL_LOG_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 21. USER_COUPON 테이블의 USER_COUPON_NO 시퀀스
CREATE SEQUENCE SEQ_USER_COUPON_NO
START WITH 1
INCREMENT BY 1
NOCACHE;
