-- USERS 테이블에 관리자 데이터 삽입
INSERT INTO USERS (USER_NO, USER_ID, PASSWORD, NAME, EMAIL, USER_TYPE, IS_DELETED, CREATED_AT, UPDATED_AT)
VALUES (1, 'admin', '1234', '관리자', 'admin@example.com', 'ADMIN', 'N', SYSDATE, SYSDATE);

-- ADMIN 테이블에 관리자 역할 데이터 삽입
INSERT INTO ADMIN (USER_NO, ROLE_CODE)
VALUES (1, 'ADMIN001');

-- USERS 테이블에 고객 데이터 삽입
INSERT INTO USERS (USER_NO, USER_ID, PASSWORD, NAME, EMAIL, USER_TYPE, IS_DELETED, CREATED_AT, UPDATED_AT)
VALUES (2, 'Tester', '1234', '고객1', 'tester@example.com', 'CUSTOMER', 'N', SYSDATE, SYSDATE);

-- CUSTOMER 테이블에 고객 정보 데이터 삽입
INSERT INTO CUSTOMER (USER_NO, AGE, JOB, LOCATION, MILEAGE, LAST_LOGIN_DATE, TOTAL_PURCHASE_AMOUNT)
VALUES (2, 30, '프로그래머', '서울', 1000, SYSDATE, 50000);

commit;